name: InspectorUHC
version: 1.0-SNAPSHOT
description: An original UHC plugin.
main: me.pjsph.inspectoruhc.InspectorUHC
author: pjsph
depend: [ProtocolLib]

commands:
  iu:
    description: InspectorUHC base command
    usage: /<ommand> <subcommand>

  f:
    description: Enable/disable the serial killer aura
    usage: /<command> <subcommand>

permissions:
  iu.*:
    description: Gives access to all /iu commands.
    default: op
    children:
      iu.start: true

  f:
    description: Allows a player to /f
    default: true